### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rodrigomedeirosbrazil** [rodrigomedeirosbrazil/flybygps#1]
- [x] Put waypoint name
- [x] Move compass needle to waypoint direction
- [x] Calc speed relative to waypoint (and ETA)
- [ ] Check timeout gps signal
- [ ] Create icon for gps signal
- [ ] Add sensors (barometer)
